sources:
  - type: csv
    sourceName: Customers
    filePath: D:/ETLDemo/data/Customers.csv
    delimiter: ","
    columns:
      - name: id
        type: int
      - name: name
        type: String
      - name: email
        type: String