target:
  type: xml
  packageName: com.etl.models.target
  className: Customers
  fields:
    - name: id
      type: int
    - name: name
      type: String
    - name: email
      type: String
    - name: phone
      type: String
