target:
  type: xml
  packageName: com.etl.models.target
  filePath: D:/ETLDemo/data/output/customers.xml
  targetName: Customers
  fields:
    - name: id
      type: int
    - name: name
      type: String
    - name: email
      type: String